version: '3.7'
services:
  signaling-server:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - media_server
    environment:
      - WS_URI=ws://localhost:8888/kurento
    network_mode: host
  media_server:
    image: kurento/kurento-media-server:6.18.0
    restart: always
    ports:
      - 8888:8888
    network_mode: host
